import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../supabaseClient';
type Customer={id:string;name:string;email:string;business:string|null;status:string|null;access_status:string;admin_notes:string|null;created_at?:string};
export function CustomerManagement(){const[customers,setCustomers]=useState<Customer[]>([]);const[search,setSearch]=useState('');const[filter,setFilter]=useState('all');const[message,setMessage]=useState<string|null>(null);const[selected,setSelected]=useState<Customer|null>(null);const[notes,setNotes]=useState<{id:string;note:string;created_at:string}[]>([]);
 async function load(){const{data,error}=await supabase.from('customers').select('id,name,email,business,status,access_status,admin_notes,created_at').order('created_at',{ascending:false});setCustomers((data??[]) as Customer[]);if(error)setMessage(error.message)}useEffect(()=>{void load()},[]);const rows=useMemo(()=>customers.filter(c=>(filter==='all'||c.access_status===filter)&&`${c.name} ${c.email} ${c.business??''}`.toLowerCase().includes(search.toLowerCase())),[customers,filter,search]);
 async function setAccess(customer:Customer,status:'active'|'blocked'|'suspended'|'deleted'){if(status==='deleted'&&!window.confirm('Remove this customer’s portal access? Their data will remain safely stored.'))return;const updates={access_status:status,blocked_at:status==='blocked'?new Date().toISOString():null,suspended_at:status==='suspended'?new Date().toISOString():null,deleted_at:status==='deleted'?new Date().toISOString():null};const{error}=await supabase.from('customers').update(updates).eq('id',customer.id);setMessage(error?error.message:`${customer.name} is now ${status}.`);await load();}
 async function open(customer:Customer){setSelected(customer);const{data,error}=await supabase.from('customer_notes').select('id,note,created_at').eq('customer_id',customer.id).order('created_at',{ascending:false});setNotes((data??[]) as {id:string;note:string;created_at:string}[]);if(error)setMessage(error.message)}
 async function saveNotes(){if(!selected)return;const text=window.prompt('Add an internal customer note:');if(!text?.trim())return;const{error}=await supabase.from('customer_notes').insert({customer_id:selected.id,note:text.trim()});if(error)setMessage(error.message);else await open(selected)}
 async function reset(customer:Customer){const{error}=await supabase.auth.resetPasswordForEmail(customer.email,{redirectTo:window.location.origin});setMessage(error?error.message:`Password reset email sent to ${customer.email}.`)}
 return <section className="management-panel"><div className="management-heading"><div><p className="eyebrow">CUSTOMER MANAGEMENT</p><h2>Customer access and history</h2><p>Review customers, control portal access, and keep private operational notes.</p></div></div>{message&&<p className="notice">{message}</p>}<div className="customer-management"><div className="list-card"><div className="list-toolbar"><input placeholder="Search customers" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All customers</option><option value="active">Active</option><option value="blocked">Blocked</option><option value="suspended">Suspended</option><option value="deleted">Removed</option></select></div><div className="customer-list">{rows.map(customer=><article key={customer.id}><div><b>{customer.name}</b><p>{customer.email} · {customer.business||'Customer'}</p><small className="status-pill">{customer.access_status}</small></div><div className="row-actions"><button onClick={()=>void open(customer)}>View</button>{customer.access_status==='blocked'?<button onClick={()=>void setAccess(customer,'active')}>Unblock</button>:<button onClick={()=>void setAccess(customer,'blocked')}>Block</button>}<button onClick={()=>void setAccess(customer,'suspended')}>Suspend</button><button className="danger" onClick={()=>void setAccess(customer,'deleted')}>Remove</button></div></article>)}{rows.length===0&&<p className="empty">No customers match this filter.</p>}</div></div>{selected&&<aside className="customer-detail"><button className="close-button" onClick={()=>setSelected(null)}>×</button><h3>{selected.name}</h3><p>{selected.email}</p><span className="status-pill">Portal: {selected.access_status}</span><button onClick={()=>void reset(selected)}>Send password reset</button><button onClick={()=>void saveNotes()}>Add customer note</button><h4>Activity & notes</h4>{notes.map(note=><p className="note" key={note.id}>{note.note}<small>{new Date(note.created_at).toLocaleString()}</small></p>)}{notes.length===0&&<p className="empty">No internal notes yet.</p>}<p className="analytics-note">Purchase history will appear here when booking/purchase payments are recorded.</p></aside>}</div></section>}
