import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../supabaseClient';

type Mode = 'history' | 'reports';
type Booking = { id:string; customer_id:string; date:string; status:string; customers:{name:string;business:string|null}|null; services:{name:string;price:number}|null };
type Request = { id:string; created_at:string; status:string };
type Activity = { id:string; action:string; entity_type:string; created_at:string; detail:Record<string,unknown> };
const businesses = ['All businesses','Alessandro Classic Barbershop',"Alessandro's Elite Fashion",'Alessandro Soft Loans','Alessandro Mobile Money',"Alessandro's Tech Solutions"];
const day = (value:string) => new Date(value).toLocaleDateString('en-CA', { timeZone:'Africa/Lusaka' });
const dateNow = () => new Date().toLocaleDateString('en-CA', { timeZone:'Africa/Lusaka' });
const money = (value:number) => new Intl.NumberFormat('en-ZM',{style:'currency',currency:'ZMW'}).format(value);

export function DashboardHistoryReports({ mode }: { mode:Mode }) {
  const [bookings,setBookings] = useState<Booking[]>([]); const [requests,setRequests] = useState<Request[]>([]); const [activities,setActivities] = useState<Activity[]>([]);
  const [singleDate,setSingleDate] = useState(mode === 'reports' ? dateNow() : ''); const [start,setStart] = useState(''); const [end,setEnd] = useState(''); const [business,setBusiness] = useState('All businesses'); const [search,setSearch] = useState(''); const [error,setError] = useState<string | null>(null);
  async function load(){
    const [bookingRes,requestRes,activityRes] = await Promise.all([
      supabase.from('bookings').select('id,customer_id,date,status,customers:customer_id(name,business),services:service_id(name,price)').order('date',{ascending:false}),
      supabase.from('requests').select('id,created_at,status').order('created_at',{ascending:false}),
      supabase.from('audit_logs').select('id,action,entity_type,created_at,detail').order('created_at',{ascending:false}).limit(500),
    ]);
    setBookings((bookingRes.data ?? []) as unknown as Booking[]); setRequests((requestRes.data ?? []) as Request[]); setActivities((activityRes.data ?? []) as Activity[]); setError(bookingRes.error?.message ?? requestRes.error?.message ?? activityRes.error?.message ?? null);
  }
  useEffect(()=>{ void load(); const channel=supabase.channel(`dashboard-${mode}-history`).on('postgres_changes',{event:'*',schema:'public',table:'bookings'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'requests'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'audit_logs'},()=>void load()).subscribe(); return()=>{void supabase.removeChannel(channel)}; },[mode]);
  const rows = useMemo(()=>bookings.filter(row=>{
    const rowDay=day(row.date); const withinSingle=!singleDate||rowDay===singleDate; const withinStart=!start||rowDay>=start; const withinEnd=!end||rowDay<=end; const inBusiness=business==='All businesses'||row.customers?.business===business; const text=`${row.customers?.name ?? ''} ${row.services?.name ?? ''} ${row.status}`.toLowerCase(); return withinSingle&&withinStart&&withinEnd&&inBusiness&&(!search||text.includes(search.toLowerCase()));
  }),[bookings,singleDate,start,end,business,search]);
  const completed=rows.filter(row=>row.status.toLowerCase()==='completed'); const attended=new Set(completed.map(row=>row.customer_id)).size; const revenue=completed.reduce((total,row)=>total+Number(row.services?.price ?? 0),0); const filteredActivities=activities.filter(row=>{const rowDay=day(row.created_at);return (!singleDate||rowDay===singleDate)&&(!start||rowDay>=start)&&(!end||rowDay<=end)}); const pending=rows.filter(row=>['pending','confirmed'].includes(row.status.toLowerCase())).length+requests.filter(row=>{const d=day(row.created_at);return (!singleDate||d===singleDate)&&(!start||d>=start)&&(!end||d<=end)&&!['completed','resolved','closed','cancelled'].includes(row.status.toLowerCase())}).length; const completedNotices=completed.length+requests.filter(row=>['completed','resolved','closed'].includes(row.status.toLowerCase())&&(!singleDate||day(row.created_at)===singleDate)).length;
  const exportCsv=()=>{const contents=['Date,Customer,Business,Service,Status,Revenue',...rows.map(row=>[row.date,row.customers?.name??'',row.customers?.business??'',row.services?.name??'',row.status,Number(row.services?.price??0)].map(value=>`"${String(value).replace(/"/g,'""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob([contents],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download=`alessandro-${mode}.csv`;link.click();URL.revokeObjectURL(url);};
  const byBusiness=useMemo(()=>businesses.slice(1).map(name=>{const businessRows=rows.filter(row=>row.customers?.business===name);const done=businessRows.filter(row=>row.status.toLowerCase()==='completed');return {name,completed:done.length,revenue:done.reduce((total,row)=>total+Number(row.services?.price??0),0)}}).filter(row=>row.completed>0||business==='All businesses'),[rows,business]);
  return <section className="dashboard-report-page"><div className="report-page-head"><div><p className="eyebrow">{mode === 'history' ? 'PERMANENT RECORDS' : 'LIVE SUPABASE REPORTING'}</p><h1>{mode === 'history' ? 'History' : 'Reports'}</h1><p>{mode === 'history' ? 'Historical records are retained permanently. Daily counters reset only in Overview.' : 'Use a date, date range, or business to review actual completed work.'}</p></div><div className="management-actions"><button onClick={exportCsv}>Export CSV</button><button onClick={()=>window.print()}>Print / PDF</button></div></div>{error&&<p className="error">{error}</p>}<div className="report-filters"><label>{mode==='reports'?'Single date':'Date'}<input type="date" value={singleDate} onChange={e=>setSingleDate(e.target.value)}/></label><label>From<input type="date" value={start} onChange={e=>{setStart(e.target.value);setSingleDate('')}}/></label><label>To<input type="date" value={end} onChange={e=>{setEnd(e.target.value);setSingleDate('')}}/></label><label>Business<select value={business} onChange={e=>setBusiness(e.target.value)}>{businesses.map(value=><option key={value}>{value}</option>)}</select></label>{mode==='history'&&<label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Customer or service"/></label>}<button className="secondary" onClick={()=>{setSingleDate(mode==='reports'?dateNow():'');setStart('');setEnd('');setBusiness('All businesses');setSearch('')}}>Reset</button></div><div className="report-summary"><b>{attended}<small>Customers attended</small></b><b>{completed.length}<small>Services completed</small></b><b>{money(revenue)}<small>Total revenue</small></b><b>{pending} / {completedNotices}<small>Pending / completed notifications</small></b></div>{mode==='reports'&&<section className="panel performance-summary"><h2>Business performance summary</h2>{byBusiness.map(row=><article key={row.name}><b>{row.name}</b><span>{row.completed} completed service{row.completed===1?'':'s'}</span><strong>{money(row.revenue)}</strong></article>)}{byBusiness.length===0&&<p className="empty">No completed services match this report.</p>}</section>}<section className="panel history-records"><h2>{mode==='history'?'Activities and records':'Bookings in this report'}</h2>{mode==='history'?filteredActivities.map(row=><article key={row.id}><b>{row.action}</b><span>{row.entity_type.replace('_',' ')}</span><time>{new Date(row.created_at).toLocaleString()}</time></article>):rows.map(row=><article key={row.id}><b>{row.customers?.name??'Customer'}</b><span>{row.customers?.business??'General'} · {row.services?.name??'Service'} · {row.status}</span><time>{new Date(row.date).toLocaleString()}</time></article>)}{(mode==='history'?filteredActivities:rows).length===0&&<p className="empty">No records match these filters.</p>}</section></section>;
}
