import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../supabaseClient';
type Promotion = { id:string; title:string; description:string|null; discount:number; active:boolean; status:string; start_date:string|null; end_date:string|null; ended_at:string|null };
const empty = { title:'', description:'', discount:'', start_date:'', end_date:'', active:true };
export function PromotionManagement() {
 const [items,setItems]=useState<Promotion[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<Promotion|null>(null); const [message,setMessage]=useState<string|null>(null); const [history,setHistory]=useState<{id:string;action:string;created_at:string}[]>([]);
 async function load(){ await supabase.rpc('expire_promotions'); const {data,error}=await supabase.from('promotions').select('id,title,description,discount,active,status,start_date,end_date,ended_at').order('updated_at',{ascending:false}); setItems((data??[]) as Promotion[]); if(error)setMessage(error.message); }
 useEffect(()=>{void load();},[]);
 async function save(e:FormEvent){e.preventDefault(); const now=new Date(); const start=form.start_date?new Date(form.start_date):null; const end=form.end_date?new Date(form.end_date):null; const status=end&&end<=now?'ended':start&&start>now?'scheduled':form.active?'active':'draft'; const payload={title:form.title.trim(),description:form.description.trim()||null,discount:Number(form.discount),start_date:form.start_date||null,end_date:form.end_date||null,active:status==='active'||status==='scheduled',status}; const query=editing?supabase.from('promotions').update(payload).eq('id',editing.id):supabase.from('promotions').insert(payload); const {error}=await query; setMessage(error?error.message:editing?'Promotion updated.':'Promotion created.'); if(!error){setEditing(null);setForm(empty);await load();}}
 function edit(item:Promotion){setEditing(item);setForm({title:item.title,description:item.description??'',discount:String(item.discount),start_date:item.start_date?.slice(0,16)??'',end_date:item.end_date?.slice(0,16)??'',active:item.active});}
 async function end(item:Promotion){const {error}=await supabase.from('promotions').update({active:false,status:'ended',ended_at:new Date().toISOString()}).eq('id',item.id);setMessage(error?error.message:'Promotion ended.');await load();}
 async function duplicate(item:Promotion){const {error}=await supabase.from('promotions').insert({title:`${item.title} (copy)`,description:item.description,discount:item.discount,active:false,status:'draft',duplicated_from:item.id});setMessage(error?error.message:'Promotion duplicated as a draft.');await load();}
 async function remove(item:Promotion){if(!window.confirm('Delete this promotion and its history?'))return;const {error}=await supabase.from('promotions').delete().eq('id',item.id);setMessage(error?error.message:'Promotion deleted.');await load();}
 async function showHistory(item:Promotion){const {data,error}=await supabase.from('promotion_history').select('id,action,created_at').eq('promotion_id',item.id).order('created_at',{ascending:false});setHistory((data??[]) as {id:string;action:string;created_at:string}[]);setMessage(error?error.message:`History for ${item.title}`);}
 return <section className="management-panel promotions-management"><div className="management-heading"><div><p className="eyebrow">PROMOTIONS</p><h2>Campaign manager</h2><p>Schedule offers, manage their lifecycle, and view their recorded history.</p></div></div>{message&&<p className="notice">{message}</p>}<div className="management-grid"><form className="editor-card" onSubmit={save}><h3>{editing?'Edit promotion':'Create promotion'}</h3><input required placeholder="Promotion title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input required type="number" min="0" step="0.01" placeholder="Discount %" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/><label>Start date (optional)<input type="datetime-local" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>End date (optional)<input type="datetime-local" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label><button>{editing?'Save promotion':'Create promotion'}</button></form><div className="list-card"><div className="promotion-list">{items.map(item=><article key={item.id}><div><b>{item.title}</b><p>{item.discount}% off · <span className="status-pill">{item.status}</span></p><small>{item.start_date?`Starts ${new Date(item.start_date).toLocaleDateString()}`:'Starts now'} {item.end_date?`· Ends ${new Date(item.end_date).toLocaleDateString()}`:'· No end date'}</small></div><div className="row-actions"><button onClick={()=>edit(item)}>Edit</button><button onClick={()=>void duplicate(item)}>Duplicate</button><button onClick={()=>void showHistory(item)}>History</button>{item.status!=='ended'&&<button onClick={()=>void end(item)}>End</button>}<button className="danger" onClick={()=>void remove(item)}>Delete</button></div></article>)}{items.length===0&&<p className="empty">No promotions yet.</p>}</div>{history.length>0&&<div className="history-box"><b>Promotion history</b>{history.map(row=><span key={row.id}>{row.action} · {new Date(row.created_at).toLocaleString()}</span>)}</div>}<p className="analytics-note">Analytics are ready for promotion history. Redemption analytics will begin when a promotion is linked to a booking or purchase.</p></div></div></section>;
}
