import { useEffect, useState } from 'react';
import { supabase } from '../supabaseClient';

type Flag = { key:string; description:string|null; enabled:boolean };
type Audit = { id:string; action:string; entity_type:string; entity_id:string|null; created_at:string };
type ErrorLog = { id:string; source:string; message:string; resolved_at:string|null; created_at:string };

export function SuperAdminPanel(){const[flags,setFlags]=useState<Flag[]>([]);const[audits,setAudits]=useState<Audit[]>([]);const[errors,setErrors]=useState<ErrorLog[]>([]);const[health,setHealth]=useState<'Checking'|'Healthy'|'Attention needed'>('Checking');const[message,setMessage]=useState<string|null>(null);const[performanceMs,setPerformanceMs]=useState<number|null>(null);
 async function load(){const started=performance.now();const[f,a,e,c,b]=await Promise.all([supabase.from('feature_flags').select('key,description,enabled').order('key'),supabase.from('audit_logs').select('id,action,entity_type,entity_id,created_at').order('created_at',{ascending:false}).limit(12),supabase.from('system_error_logs').select('id,source,message,resolved_at,created_at').order('created_at',{ascending:false}).limit(12),supabase.from('customers').select('id',{head:true,count:'exact'}),supabase.from('bookings').select('id',{head:true,count:'exact'})]);setPerformanceMs(Math.round(performance.now()-started));setFlags((f.data??[])as Flag[]);setAudits((a.data??[])as Audit[]);setErrors((e.data??[])as ErrorLog[]);setHealth(f.error||a.error||e.error||c.error||b.error?'Attention needed':'Healthy');if(f.error||a.error||e.error)setMessage(f.error?.message??a.error?.message??e.error?.message??'System data could not load.');}
 useEffect(()=>{void load();},[]);
 async function toggle(flag:Flag){const{error}=await supabase.from('feature_flags').update({enabled:!flag.enabled,updated_by:(await supabase.auth.getUser()).data.user?.id}).eq('key',flag.key);setMessage(error?error.message:`${flag.key} ${flag.enabled?'disabled':'enabled'}.`);await load();}
 async function resolve(error:ErrorLog){const{error:saveError}=await supabase.from('system_error_logs').update({resolved_at:new Date().toISOString()}).eq('id',error.id);setMessage(saveError?saveError.message:'Error marked resolved.');await load();}
 async function logTest(){const{error}=await supabase.from('system_error_logs').insert({source:'super-admin-check',message:'Manual diagnostic test entry'});setMessage(error?error.message:'Diagnostic entry recorded.');await load();}
 return <section className="super-admin-panel"><div className="super-admin-heading"><div><p className="eyebrow">RESTRICTED AREA</p><h2>Super Admin operations</h2><p>System health, feature controls, audit visibility and safe operational diagnostics.</p></div><span className={`health ${health.toLowerCase().replaceAll(' ','-')}`}>{health}</span></div>{message&&<p className="notice">{message}</p>}<div className="health-grid"><article><b>{performanceMs ?? '—'} ms</b><span>Database health check</span></article><article><b>{import.meta.env.VITE_SUPABASE_URL ? 'Configured' : 'Missing'}</b><span>Environment configuration</span></article><article><b>RLS</b><span>Permission model enforced</span></article><article><b>1.0.0</b><span>Dashboard version</span></article></div><div className="super-grid"><div className="super-card"><h3>Feature toggles</h3>{flags.map(flag=><div className="flag-row" key={flag.key}><div><b>{flag.key.replaceAll('_',' ')}</b><p>{flag.description}</p></div><button onClick={()=>void toggle(flag)}>{flag.enabled?'Enabled':'Disabled'}</button></div>)}{flags.length===0&&<p className="empty">No feature flags configured.</p>}</div><div className="super-card"><h3>Developer tools</h3><p>Use a harmless test record to verify error logging and access controls.</p><button onClick={()=>void logTest()}>Run diagnostic log test</button><p className="analytics-note">Storage quotas, database backups, restore, impersonation, and service-role credentials are deliberately unavailable in the browser. Use protected Supabase administration tools or Edge Functions.</p></div></div><div className="super-grid"><div className="super-card"><h3>Audit logs</h3><div className="mini-log">{audits.map(audit=><p key={audit.id}><b>{audit.action}</b> · {audit.entity_type} <small>{new Date(audit.created_at).toLocaleString()}</small></p>)}{audits.length===0&&<p className="empty">No audit records yet.</p>}</div></div><div className="super-card"><h3>Error logs</h3><div className="mini-log">{errors.map(error=><p key={error.id}><b>{error.source}</b> · {error.message}<small>{new Date(error.created_at).toLocaleString()}</small>{!error.resolved_at&&<button onClick={()=>void resolve(error)}>Resolve</button>}</p>)}{errors.length===0&&<p className="empty">No active error records.</p>}</div></div></div></section>}
