import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { supabase } from './supabaseClient';
import { AdminSettings } from './components/AdminSettings';
import { ProductManagement } from './components/ProductManagement';
import { PromotionManagement } from './components/PromotionManagement';
import { CustomerManagement } from './components/CustomerManagement';
import { OperationsControlCenter } from './components/OperationsControlCenter';
import { SuperAdminPanel } from './components/SuperAdminPanel';
import { EmployeeManagement } from './components/EmployeeManagement';
import { BusinessReports } from './components/BusinessReports';
import { ActivityHistory } from './components/ActivityHistory';
import { WebsiteManagement } from './components/WebsiteManagement';
import './App.css';

type Customer = { id: string; name: string; email: string; phone: string | null; business: string | null; status: string };
type Service = { id: string; name: string; description: string | null; duration: number | null; price: number; active: boolean };
type Promotion = { id: string; title: string; description: string | null; discount: number; active: boolean };
type Booking = { id: string; date: string; notes: string | null; status: string; customers: Customer | null; services: Service | null };
type Message = { id: string; subject: string; body: string; sent_at: string; status: string; customers: Customer | null };
type Request = { id: string; request_type: string; description: string; created_at: string; status: string; customers: Customer | null };
type Email = { id: string; subject: string; body: string; sent_at: string; status: string; customers: Customer | null };
type Activity = { id: string; label: string; detail: string; time: string; icon: string };
type DashboardView = 'overview' | 'bookings' | 'requests' | 'customers' | 'catalogue' | 'settings';

function Login({ onSession }: { onSession: (session: Session) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) {
    event.preventDefault(); setLoading(true); setError(null);
    const { data, error: signInError } = await supabase.auth.signInWithPassword({ email, password });
    if (signInError || !data.session) { setError(signInError?.message ?? 'Unable to sign in.'); setLoading(false); return; }
    if (!['admin', 'super_admin'].includes(data.user.app_metadata?.role)) { await supabase.auth.signOut(); setError('This account is not authorised to use the admin dashboard.'); setLoading(false); return; }
    onSession(data.session); setLoading(false);
  }
  return <main className="auth"><form onSubmit={submit} className="auth-card"><img src="/logos/alessandroenterprises.png" alt="Alessandro Enterprises" /><p className="eyebrow">ADMIN WORKSPACE</p><h1>Welcome back</h1><p>Sign in to manage your live customer portal.</p><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <p className="error">{error}</p>}<button disabled={loading}>{loading ? 'Signing in…' : 'Sign in to dashboard'}</button></form></main>;
}

function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [bookings, setBookings] = useState<Booking[]>([]); const [messages, setMessages] = useState<Message[]>([]);
  const [requests, setRequests] = useState<Request[]>([]); const [emails, setEmails] = useState<Email[]>([]);
  const [services, setServices] = useState<Service[]>([]); const [promotions, setPromotions] = useState<Promotion[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [websiteVisitors, setWebsiteVisitors] = useState<number | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [search, setSearch] = useState(''); const [sidebarOpen, setSidebarOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [activeView, setActiveView] = useState<DashboardView>('overview');
  const [serviceName, setServiceName] = useState(''); const [servicePrice, setServicePrice] = useState(''); const [promotionTitle, setPromotionTitle] = useState(''); const [promotionDiscount, setPromotionDiscount] = useState('');

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    const [bookingRes, messageRes, requestRes, emailRes, serviceRes, promotionRes, customerRes] = await Promise.all([
      supabase.from('bookings').select('id,date,notes,status,customers:customer_id(id,name,email,phone,business,status),services:service_id(id,name,description,duration,price,active)').order('date', { ascending: false }),
      supabase.from('messages').select('id,subject,body,sent_at,status,customers:customer_id(id,name,email,phone,business,status)').order('sent_at', { ascending: false }),
      supabase.from('requests').select('id,request_type,description,created_at,status,customers:customer_id(id,name,email,phone,business,status)').order('created_at', { ascending: false }),
      supabase.from('emails').select('id,subject,body,sent_at,status,customers:customer_id(id,name,email,phone,business,status)').order('sent_at', { ascending: false }),
      supabase.from('services').select('id,name,description,duration,price,active').order('name'),
      supabase.from('promotions').select('id,title,description,discount,active').order('title'),
      supabase.from('customers').select('id,name,email,phone,business,status').order('created_at', { ascending: false }),
    ]);
    const results = [bookingRes, messageRes, requestRes, emailRes, serviceRes, promotionRes, customerRes]; const firstError = results.find((result) => result.error)?.error;
    if (firstError) setError(firstError.message);
    setBookings((bookingRes.data ?? []) as unknown as Booking[]); setMessages((messageRes.data ?? []) as unknown as Message[]); setRequests((requestRes.data ?? []) as unknown as Request[]); setEmails((emailRes.data ?? []) as unknown as Email[]);
    setServices((serviceRes.data ?? []) as Service[]); setPromotions((promotionRes.data ?? []) as Promotion[]); setCustomers((customerRes.data ?? []) as Customer[]); setLoading(false);
  }, []);

  useEffect(() => { supabase.auth.getSession().then(({ data }) => { if (['admin', 'super_admin'].includes(data.session?.user.app_metadata?.role)) setSession(data.session); setLoading(false); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(['admin', 'super_admin'].includes(nextSession?.user.app_metadata?.role) ? nextSession : null)); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session) return; void load(); const channel = supabase.channel(`admin-dashboard:${session.user.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'bookings' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'messages' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'requests' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'emails' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'services' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'promotions' }, () => void load()).on('postgres_changes', { event: '*', schema: 'public', table: 'customers' }, () => void load()).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [session, load]);
  useEffect(() => { document.querySelectorAll<HTMLElement>('#catalogue .records span').forEach((element) => { if (element.textContent?.startsWith('$')) element.textContent = `K${element.textContent.slice(1)}`; }); }, [services]);
  useEffect(() => { const onHashChange = () => { const next = window.location.hash.slice(1); if (['overview', 'bookings', 'requests', 'customers', 'catalogue', 'settings'].includes(next)) setActiveView(next as DashboardView); }; window.addEventListener('hashchange', onHashChange); onHashChange(); return () => window.removeEventListener('hashchange', onHashChange); }, []);

  async function updateStatus(table: 'bookings' | 'messages' | 'requests' | 'emails', id: string, status: string) { const { error: updateError } = await supabase.from(table).update({ status }).eq('id', id); if (updateError) setError(updateError.message); else { setNotice('Status updated.'); void load(); } }
  async function addService(event: FormEvent) { event.preventDefault(); const { error: insertError } = await supabase.from('services').insert({ name: serviceName.trim(), price: Number(servicePrice), active: true }); if (insertError) setError(insertError.message); else { setServiceName(''); setServicePrice(''); setNotice('Service created.'); void load(); } }
  async function addPromotion(event: FormEvent) { event.preventDefault(); const { error: insertError } = await supabase.from('promotions').insert({ title: promotionTitle.trim(), discount: Number(promotionDiscount), active: true }); if (insertError) setError(insertError.message); else { setPromotionTitle(''); setPromotionDiscount(''); setNotice('Promotion created.'); void load(); } }
  async function signOut() { await supabase.auth.signOut(); setSession(null); }
  function selectView(view: DashboardView) { setActiveView(view); setSidebarOpen(false); setProfileOpen(false); setNotificationsOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }

  const pendingRequests = requests.filter((request) => !['completed', 'resolved', 'closed', 'cancelled'].includes(request.status.toLowerCase())).length;
  const completedRequests = requests.filter((request) => ['completed', 'resolved', 'closed'].includes(request.status.toLowerCase())).length;
  const activePromotions = promotions.filter((promotion) => promotion.active).length;
  const unreadNotificationCount = [...messages, ...requests, ...emails].filter((item) => !['completed', 'closed', 'resolved', 'read', 'cancelled'].includes(item.status.toLowerCase())).length;
  const revenue = bookings.filter((booking) => booking.status.toLowerCase() === 'completed').reduce((total, booking) => total + Number(booking.services?.price ?? 0), 0);
  const activities = useMemo<Activity[]>(() => [...bookings.map((item) => ({ id: `b-${item.id}`, label: 'Booking created', detail: `${item.customers?.name ?? 'Customer'} · ${item.services?.name ?? 'Service'}`, time: item.date, icon: '◷' })), ...messages.map((item) => ({ id: `m-${item.id}`, label: 'New message', detail: `${item.customers?.name ?? 'Customer'} · ${item.subject}`, time: item.sent_at, icon: '✉' })), ...requests.map((item) => ({ id: `r-${item.id}`, label: 'Request submitted', detail: `${item.customers?.name ?? 'Customer'} · ${item.request_type}`, time: item.created_at, icon: '↗' }))].sort((a, b) => new Date(b.time).getTime() - new Date(a.time).getTime()), [bookings, messages, requests]);
  const query = search.trim().toLowerCase(); const filteredBookings = query ? bookings.filter((row) => `${row.customers?.name} ${row.services?.name} ${row.status}`.toLowerCase().includes(query)) : bookings;
  useEffect(() => { let mounted = true; const renderBadge = (count: number) => { const badge = document.querySelector<HTMLElement>('.notification-wrap .icon-button i'); if (!badge || !mounted) return; badge.textContent = count ? String(count) : ''; badge.style.display = count ? 'grid' : 'none'; }; const refreshBadge = async () => { const { count } = await supabase.from('admin_notifications').select('*', { count: 'exact', head: true }).is('read_at', null).is('completed_at', null).is('archived_at', null); renderBadge(count ?? 0); }; void refreshBadge(); const channel = supabase.channel(`notification-badge:${session?.user.id ?? 'guest'}`).on('postgres_changes', { event: '*', schema: 'public', table: 'admin_notifications' }, () => void refreshBadge()).subscribe(); return () => { mounted = false; void supabase.removeChannel(channel); }; }, [session]);
  useEffect(() => { if (!session) return; const refreshVisitors = async () => { const { count } = await supabase.from('website_visits').select('*', { count: 'exact', head: true }); setWebsiteVisitors(count ?? 0); }; void refreshVisitors(); const channel = supabase.channel(`website-visitors:${session.user.id}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'website_visits' }, () => void refreshVisitors()).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [session]);
  if (!session) return <Login onSession={setSession} />;
  const firstName = session.user.email?.split('@')[0] ?? 'Administrator';

  return <div className="app-shell">
    <aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}><div className="sidebar-brand"><img src="/logos/alessandroenterprises.png" alt="Alessandro Enterprises" /><div><strong>Alessandro</strong><span>Admin Workspace</span></div></div><nav className="side-nav"><button className={activeView === 'overview' ? 'selected' : ''} onClick={() => selectView('overview')}>⌂ <span>Overview</span></button><button className={activeView === 'bookings' ? 'selected' : ''} onClick={() => selectView('bookings')}>◷ <span>Bookings</span></button><button className={activeView === 'requests' ? 'selected' : ''} onClick={() => selectView('requests')}>↗ <span>Requests</span></button><button className={activeView === 'customers' ? 'selected' : ''} onClick={() => selectView('customers')}>♙ <span>Customers</span></button><button className={activeView === 'catalogue' ? 'selected' : ''} onClick={() => selectView('catalogue')}>◇ <span>Catalogue</span></button><a href="https://alessandros-enterprises.vercel.app" target="_blank" rel="noreferrer">↗ <span>Website</span></a></nav><div className="sidebar-help"><b>Need a quick update?</b><span>New bookings and requests refresh automatically.</span><button onClick={() => void load()}>↻ Refresh data</button></div></aside>
    {sidebarOpen && <button className="mobile-overlay" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
    <div className="page"><header className="topbar"><button className="menu-button" aria-label="Open navigation" onClick={() => setSidebarOpen(true)}>☰</button><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search bookings, customers, services…" /></label><div className="topbar-actions"><div className="notification-wrap"><button className="icon-button" aria-label="Notifications" onClick={() => setNotificationsOpen((current) => !current)}>♟<i>{pendingRequests + messages.length}</i></button>{notificationsOpen && <div className="popover notifications"><b>Notifications</b><p>{pendingRequests} request{pendingRequests === 1 ? '' : 's'} awaiting attention.</p><p>{messages.length} customer message{messages.length === 1 ? '' : 's'} received.</p><button className="text-button" onClick={() => selectView('requests')}>View requests →</button></div>}</div><div className="profile-wrap"><button className="profile-button" onClick={() => setProfileOpen((current) => !current)}><span>{firstName.slice(0, 1).toUpperCase()}</span><div><b>Account</b><small>Administrator</small></div><em>⌄</em></button>{profileOpen && <div className="popover profile-menu"><span>{session.user.email}</span><button onClick={() => selectView('settings')}>Business settings</button><button onClick={() => void signOut()}>Sign out</button></div>}</div></div></header>
    <main className={`dashboard-main view-${activeView}`}><section id="overview" className="welcome view-only overview-view"><div><p className="eyebrow">LIVE BUSINESS OVERVIEW</p><h1>Good to see you.</h1><p>Everything happening across your customer portal, in one clear workspace.</p></div><div className="quick-actions"><button onClick={() => selectView('catalogue')}>＋ Add service</button><button className="secondary" onClick={() => selectView('catalogue')}>✦ New promotion</button><button className="secondary" onClick={() => void load()}>↻ Refresh</button></div></section>
      {error && <p className="error dashboard-alert">{error}</p>}{notice && <p className="notice dashboard-alert">{notice}</p>}
      {loading ? <div className="loading-card">Loading your live business data…</div> : <>
        <section className="metrics-grid view-only overview-view"><Metric icon="♙" label="Total customers" value={customers.length} note="Registered portal customers" tone="blue" /><Metric icon="◇" label="Total products" value={services.length} note={`${services.filter((service) => service.active).length} currently active`} tone="gold" /><Metric icon="✦" label="Active promotions" value={activePromotions} note="Visible to customers" tone="purple" /><Metric icon="↗" label="Pending requests" value={pendingRequests} note={`${completedRequests} completed or resolved`} tone="orange" /><Metric icon="✓" label="Completed requests" value={completedRequests} note="Across all customer requests" tone="green" /><Metric icon="◉" label="Website visitors" value={websiteVisitors ?? '—'} note={websiteVisitors === null ? 'Run website migration to enable' : 'Recorded visitor sessions'} tone="slate" /><Metric icon="K" label="Revenue" value={`K${revenue.toFixed(2)}`} note="Completed bookings only" tone="teal" /><Metric icon="◷" label="Bookings" value={bookings.length} note="All service appointments" tone="pink" /></section>
        <section className="insights-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">BUSINESS STATISTICS</p><h2>Service demand</h2></div><span className="live-dot">Live</span></div><div className="bar-chart">{services.slice(0, 6).map((service) => { const count = bookings.filter((booking) => booking.services?.id === service.id).length; const height = bookings.length ? Math.max(10, (count / Math.max(...services.map((item) => bookings.filter((booking) => booking.services?.id === item.id).length), 1)) * 100) : 10; return <div className="bar-item" key={service.id}><b style={{ height: `${height}%` }} title={`${count} booking(s)`} /><span>{service.name}</span><small>{count}</small></div>; })}{services.length === 0 && <p className="empty">Add services to see demand data here.</p>}</div></article><article className="panel requests-panel"><div className="panel-heading"><div><p className="eyebrow">REQUESTS</p><h2>Work status</h2></div><a href="#requests">View all →</a></div><div className="progress-row"><span>Pending</span><b>{pendingRequests}</b><i><em style={{ width: `${requests.length ? (pendingRequests / requests.length) * 100 : 0}%` }} /></i></div><div className="progress-row"><span>Completed</span><b>{completedRequests}</b><i><em className="green" style={{ width: `${requests.length ? (completedRequests / requests.length) * 100 : 0}%` }} /></i></div><div className="stat-callout"><span>Customer messages</span><b>{messages.length}</b><small>Messages are monitored in real time.</small></div></article></section>
        <section className="content-grid"><article className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">LIVE FEED</p><h2>Recent activity</h2></div><button className="text-button" onClick={() => void load()}>Refresh</button></div><div className="activity-list">{activities.slice(0, 6).map((activity) => <div className="activity" key={activity.id}><span className="activity-icon">{activity.icon}</span><div><b>{activity.label}</b><p>{activity.detail}</p></div><time>{formatRelativeTime(activity.time)}</time></div>)}{activities.length === 0 && <p className="empty">New bookings, messages and requests will appear here.</p>}</div></article><article className="panel notifications-panel"><div className="panel-heading"><div><p className="eyebrow">ATTENTION NEEDED</p><h2>Notifications</h2></div><button className="icon-button small" onClick={() => setNotificationsOpen(true)}>♟</button></div><div className="notification-item"><span className="badge orange">{pendingRequests}</span><div><b>Pending requests</b><p>Review customer requests that still need a response.</p></div></div><div className="notification-item"><span className="badge blue">{messages.length}</span><div><b>Customer messages</b><p>New enquiries from the customer portal.</p></div></div><div className="notification-item"><span className="badge purple">{activePromotions}</span><div><b>Live promotions</b><p>Offers currently visible to customers.</p></div></div></article></section>
        <section id="bookings" className="panel data-panel"><div className="panel-heading"><div><p className="eyebrow">OPERATIONS</p><h2>Bookings</h2></div><span>{filteredBookings.length} shown</span></div><Table rows={filteredBookings} empty={query ? 'No bookings match your search.' : 'No bookings yet.'} render={(row) => <><b>{row.customers?.name ?? 'Unknown customer'}</b><span>{row.services?.name ?? 'Unknown service'} · {new Date(row.date).toLocaleString()}</span><span className="status-pill">{row.status}</span><StatusSelect value={row.status} onChange={(status) => void updateStatus('bookings', row.id, status)} /></>} /></section>
        <section id="requests" className="panel data-panel"><div className="panel-heading"><div><p className="eyebrow">CUSTOMER CARE</p><h2>Requests</h2></div><span>{requests.length} total</span></div><Table rows={requests} empty="No requests yet." render={(row) => <><b>{row.customers?.name ?? 'Unknown customer'} — {row.request_type}</b><span>{row.description}</span><span className="status-pill">{row.status}</span><StatusSelect value={row.status} onChange={(status) => void updateStatus('requests', row.id, status)} /></>} /></section>
        <section className="communication-grid"><div className="panel data-panel"><h2>Messages</h2><Table rows={messages.slice(0, 5)} empty="No messages yet." render={(row) => <><b>{row.customers?.name ?? 'Unknown customer'} — {row.subject}</b><span>{row.body}</span><StatusSelect value={row.status} onChange={(status) => void updateStatus('messages', row.id, status)} /></>} /></div><div className="panel data-panel"><h2>Emails</h2><Table rows={emails.slice(0, 5)} empty="No emails yet." render={(row) => <><b>{row.customers?.name ?? 'Unknown customer'} — {row.subject}</b><span>{row.body}</span><StatusSelect value={row.status} onChange={(status) => void updateStatus('emails', row.id, status)} /></>} /></div></section>
        <section id="catalogue" className="two-column"><div className="panel"><div className="panel-heading"><h2>Services</h2><span>{services.length} products</span></div><form onSubmit={addService} className="inline-form"><input placeholder="Service name" value={serviceName} onChange={(e) => setServiceName(e.target.value)} required /><input type="number" min="0" step="0.01" placeholder="Price" value={servicePrice} onChange={(e) => setServicePrice(e.target.value)} required /><button>Add service</button></form><Table rows={services} empty="No services." render={(row) => <><b>{row.name}</b><span>${row.price}</span><span className="status-pill">{row.active ? 'Active' : 'Inactive'}</span></>} /></div><div id="promotions" className="panel"><div className="panel-heading"><h2>Promotions</h2><span>{activePromotions} active</span></div><form onSubmit={addPromotion} className="inline-form"><input placeholder="Promotion title" value={promotionTitle} onChange={(e) => setPromotionTitle(e.target.value)} required /><input type="number" min="0" step="0.01" placeholder="Discount %" value={promotionDiscount} onChange={(e) => setPromotionDiscount(e.target.value)} required /><button>Add promotion</button></form><Table rows={promotions} empty="No promotions." render={(row) => <><b>{row.title}</b><span>{row.discount}% off</span><span className="status-pill">{row.active ? 'Active' : 'Inactive'}</span></>} /></div></section>
        <section id="customers" className="panel customer-panel"><div className="panel-heading"><div><p className="eyebrow">CUSTOMER BASE</p><h2>Customer snapshot</h2></div><span>{customers.length} registered</span></div><div className="customer-chips">{customers.slice(0, 8).map((customer) => <div key={customer.id}><b>{customer.name.slice(0, 1).toUpperCase()}</b><span>{customer.name}</span><small>{customer.business || 'Customer'}</small></div>)}{customers.length === 0 && <p className="empty">Your registered customers will appear here.</p>}</div></section>
        <section id="settings"><AdminSettings /><WebsiteManagement /><BusinessReports /><EmployeeManagement /><ActivityHistory /><OperationsControlCenter />{session.user.app_metadata?.role === 'super_admin' && <SuperAdminPanel />}</section>
        <div className="phase-management products-page"><ProductManagement /><PromotionManagement /></div>
        <div className="phase-management customers-page"><CustomerManagement /></div>
      </>}</main></div></div>;
}

function Metric({ icon, label, value, note, tone }: { icon: string; label: string; value: string | number; note: string; tone: string }) { return <article className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><div><p>{label}</p><b>{value}</b><small>{note}</small></div></article>; }
function StatusSelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <select aria-label="Update status" value={value} onClick={(event) => event.stopPropagation()} onChange={(event) => onChange(event.target.value)}><option>Pending</option><option>Open</option><option>Sent</option><option>Read</option><option>Confirmed</option><option>Completed</option><option>Resolved</option><option>Closed</option><option>Cancelled</option></select>; }
function Table<T>({ rows, empty, render }: { rows: T[]; empty: string; render: (row: T) => ReactNode }) { const [opened, setOpened] = useState<T | null>(null); const activeRows = rows.filter((row) => !['completed', 'closed', 'resolved', 'cancelled'].includes(String((row as { status?: string }).status ?? '').toLowerCase())); return <>{activeRows.length === 0 ? <p className="empty">{empty}</p> : <div className="records">{activeRows.map((row, index) => <article className="openable-record" key={index} onClick={() => setOpened(row)}>{render(row)}</article>)}</div>}{opened && <RecordPreview record={opened} onClose={() => setOpened(null)} />}</>; }
function RecordPreview({ record, onClose }: { record: unknown; onClose: () => void }) { const item = record as Record<string, unknown>; const customer = item.customers as Customer | null; const title = String(item.subject ?? item.request_type ?? item.status ?? 'Record details'); const body = String(item.body ?? item.description ?? item.notes ?? 'No additional details were provided.'); const reply = customer?.email ? `mailto:${customer.email}?subject=${encodeURIComponent(`Re: ${title}`)}` : null; return <div className="record-modal-backdrop" onClick={onClose}><article className="record-modal" role="dialog" aria-modal="true" aria-label={title} onClick={(event) => event.stopPropagation()}><button className="record-modal-close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">DETAILS</p><h2>{title}</h2>{customer && <div className="customer-contact"><b>{customer.name}</b><span>{customer.email || 'No email address'}{customer.phone ? ` · ${customer.phone}` : ''}</span></div>}<p>{body}</p><div className="record-modal-actions">{reply && <a href={reply}>Reply by email</a>}{customer?.phone && <a href={`tel:${customer.phone}`}>Call customer</a>}<button onClick={onClose}>Close</button></div></article></div>; }
function formatRelativeTime(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return 'Just now'; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago`; }
export default App;
