import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { supabase } from './supabaseClient';
import { AdminSettings } from './components/AdminSettings';
import { ProductManagement } from './components/ProductManagement';
import { PromotionManagement } from './components/PromotionManagement';
import { CustomerManagement } from './components/CustomerManagement';
import { OperationsControlCenter } from './components/OperationsControlCenter';
import { SuperAdminPanel } from './components/SuperAdminPanel';
import { EmployeeManagement } from './components/EmployeeManagement';
import { WebsiteManagement } from './components/WebsiteManagement';
import { DailyOverview } from './components/DailyOverview';
import { DashboardHistoryReports } from './components/DashboardHistoryReports';
import { ContentPostManagement } from './components/ContentPostManagement';
import './App.css';

type Customer={id:string;name:string;email:string;phone:string|null;business:string|null;status:string};
type Service={id:string;name:string;price:number};
type Booking={id:string;date:string;notes:string|null;status:string;customers:Customer|null;services:Service|null};
type Message={id:string;subject:string;body:string;sent_at:string;status:string;customers:Customer|null};
type Request={id:string;request_type:string;description:string;created_at:string;status:string;customers:Customer|null};
type Email={id:string;subject:string;body:string;sent_at:string;status:string;customers:Customer|null};
type View='overview'|'bookings'|'requests'|'customers'|'catalogue'|'history'|'reports'|'settings';
type RecordItem=Booking|Message|Request|Email;
const isAdmin=(session:Session|null)=>['admin','super_admin'].includes(session?.user.app_metadata?.role);
const isActive=(status:string)=>!['completed','resolved','closed','cancelled','archived'].includes(status.toLowerCase());

function Login({onSession}:{onSession:(session:Session)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(false);async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError(null);const{data,error:loginError}=await supabase.auth.signInWithPassword({email,password});if(loginError||!data.session){setError(loginError?.message??'Unable to sign in.');setLoading(false);return}if(!isAdmin(data.session)){await supabase.auth.signOut();setError('This account is not authorised to use the admin dashboard.');setLoading(false);return}onSession(data.session);setLoading(false)}return <main className="auth"><form onSubmit={submit} className="auth-card"><img src="/logos/alessandroenterprises.png" alt="Alessandro Enterprises"/><p className="eyebrow">ADMIN WORKSPACE</p><h1>Welcome back</h1><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button disabled={loading}>{loading?'Signing in...':'Sign in to dashboard'}</button></form></main>}

export default function App(){
 const[session,setSession]=useState<Session|null>(null);const[view,setView]=useState<View>('overview');const[sidebarOpen,setSidebarOpen]=useState(false);const[profileOpen,setProfileOpen]=useState(false);const[notificationOpen,setNotificationOpen]=useState(false);const[search,setSearch]=useState('');const[error,setError]=useState<string|null>(null);const[notificationDetail,setNotificationDetail]=useState<RecordItem|null>(null);
 const[bookings,setBookings]=useState<Booking[]>([]);const[messages,setMessages]=useState<Message[]>([]);const[requests,setRequests]=useState<Request[]>([]);const[emails,setEmails]=useState<Email[]>([]);const[adminNotificationCount,setAdminNotificationCount]=useState(0);
 const load=useCallback(async()=>{const[b,m,r,e,n]=await Promise.all([supabase.from('bookings').select('id,date,notes,status,customers:customer_id(id,name,email,phone,business,status),services:service_id(id,name,price)').order('date',{ascending:false}),supabase.from('messages').select('id,subject,body,sent_at,status,customers:customer_id(id,name,email,phone,business,status)').order('sent_at',{ascending:false}),supabase.from('requests').select('id,request_type,description,created_at,status,customers:customer_id(id,name,email,phone,business,status)').order('created_at',{ascending:false}),supabase.from('emails').select('id,subject,body,sent_at,status,customers:customer_id(id,name,email,phone,business,status)').order('sent_at',{ascending:false}),supabase.from('admin_notifications').select('id',{count:'exact',head:true}).is('archived_at',null).is('completed_at',null)]);setBookings((b.data??[])as unknown as Booking[]);setMessages((m.data??[])as unknown as Message[]);setRequests((r.data??[])as unknown as Request[]);setEmails((e.data??[])as unknown as Email[]);setAdminNotificationCount(n.count??0);setError(b.error?.message??m.error?.message??r.error?.message??e.error?.message??n.error?.message??null)},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(isAdmin(data.session))setSession(data.session)});const{data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(isAdmin(next)?next:null));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;void load();const channel=supabase.channel(`admin-main:${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'bookings'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'requests'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'emails'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'admin_notifications'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[session,load]);
 useEffect(()=>{const change=()=>{const next=window.location.hash.slice(1);if(['overview','bookings','requests','customers','catalogue','history','reports','settings'].includes(next))setView(next as View)};window.addEventListener('hashchange',change);change();return()=>window.removeEventListener('hashchange',change)},[]);
 const activeBookings=bookings.filter(row=>isActive(row.status));const activeRequests=requests.filter(row=>isActive(row.status));const activeMessages=messages.filter(row=>isActive(row.status));const activeEmails=emails.filter(row=>isActive(row.status));const upcomingBookings=activeBookings.filter(row=>['pending','confirmed'].includes(row.status.toLowerCase())).slice(0,4);const query=search.toLowerCase().trim();const foundBookings=query?activeBookings.filter(row=>`${row.customers?.name} ${row.services?.name} ${row.status}`.toLowerCase().includes(query)):activeBookings;
 const select=(next:View)=>{setView(next);window.location.hash=next;setSidebarOpen(false);setProfileOpen(false);setNotificationOpen(false);window.scrollTo({top:0,behavior:'smooth'})};const signOut=async()=>{await supabase.auth.signOut();setSession(null)};const update=async(table:'bookings'|'messages'|'requests'|'emails',id:string,status:string)=>{const{error:updateError}=await supabase.from(table).update({status}).eq('id',id);if(updateError)setError(updateError.message);else void load()};
 if(!session)return <Login onSession={setSession}/>;
 return <>
  <div className="app-shell"><aside className={`sidebar ${sidebarOpen?'sidebar-open':''}`}><div className="sidebar-brand"><img src="/logos/alessandroenterprises.png" alt="Alessandro Enterprises"/><div><strong>ALESSANDRO</strong><span>Admin Workspace</span></div></div><nav className="side-nav"><Nav view={view} id="overview" onClick={select}>Overview</Nav><Nav view={view} id="bookings" onClick={select}>Bookings</Nav><Nav view={view} id="requests" onClick={select}>Requests</Nav><Nav view={view} id="customers" onClick={select}>Customers</Nav><Nav view={view} id="catalogue" onClick={select}>Catalogue</Nav><Nav view={view} id="history" onClick={select}>History</Nav><Nav view={view} id="reports" onClick={select}>Reports</Nav><Nav view={view} id="settings" onClick={select}>Settings</Nav><a href="https://alessandros-enterprises.vercel.app" target="_blank" rel="noreferrer">Website</a></nav><div className="sidebar-help"><b>Live data connected</b><span>Bookings, requests, and activities update automatically.</span><button onClick={()=>void load()}>Refresh data</button></div></aside>{sidebarOpen&&<button className="mobile-overlay" aria-label="Close navigation" onClick={()=>setSidebarOpen(false)}/>}<div className="page">
   <header className="topbar"><button className="menu-button" onClick={()=>setSidebarOpen(true)} aria-label="Open navigation">☰</button><div className="topbar-wordmark">ALESSANDRO</div><label className="search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search bookings, customers, services..."/></label><div className="topbar-actions"><div className="notification-wrap"><button className="icon-button" onClick={()=>setNotificationOpen(!notificationOpen)} aria-label="Notifications">●{(adminNotificationCount+upcomingBookings.length+activeMessages.length)>0&&<i>{adminNotificationCount+upcomingBookings.length+activeMessages.length}</i>}</button>{notificationOpen&&<NotificationSummary bookings={upcomingBookings} messages={activeMessages.slice(0,3)} requests={activeRequests.slice(0,2)} onOpen={setNotificationDetail}/>}</div><div className="profile-wrap"><button className="profile-button" onClick={()=>setProfileOpen(!profileOpen)}><span>A</span><div><b>Account</b><small>Administrator</small></div></button>{profileOpen&&<div className="popover profile-menu"><span>{session.user.email}</span><button onClick={()=>select('settings')}>Business settings</button><button onClick={()=>void signOut()}>Sign out</button></div>}</div></div></header>
   <main className={`dashboard-main view-${view}`}>{error&&<p className="error dashboard-alert">{error}</p>}{view==='overview'&&<DailyOverview/>}{view==='history'&&<DashboardHistoryReports mode="history"/>}{view==='reports'&&<DashboardHistoryReports mode="reports"/>}{view==='bookings'&&<Operations title="Bookings" rows={foundBookings} empty="No active bookings match your search." render={row=><><b>{row.customers?.name??'Unknown customer'}</b><span>{row.services?.name??'Service'} · {new Date(row.date).toLocaleString()}</span><span className="status-pill">{row.status}</span><StatusSelect value={row.status} onChange={status=>void update('bookings',row.id,status)}/></>}/>} {view==='requests'&&<><Operations title="Requests" rows={activeRequests} empty="No active requests yet." render={row=><><b>{row.customers?.name??'Unknown customer'} — {row.request_type}</b><span>{row.description}</span><span className="status-pill">{row.status}</span><StatusSelect value={row.status} onChange={status=>void update('requests',row.id,status)}/></>}/><div className="communication-grid"><Operations title="Messages" rows={activeMessages} empty="No active messages yet." render={row=><><b>{row.customers?.name??'Customer'} — {row.subject}</b><span>{row.body}</span><StatusSelect value={row.status} onChange={status=>void update('messages',row.id,status)}/></>}/><Operations title="Emails" rows={activeEmails} empty="No active emails yet." render={row=><><b>{row.customers?.name??'Customer'} — {row.subject}</b><span>{row.body}</span><StatusSelect value={row.status} onChange={status=>void update('emails',row.id,status)}/></>}/></div></>}{view==='customers'&&<CustomerManagement/>}{view==='catalogue'&&<div className="phase-management always-visible"><ProductManagement/><PromotionManagement/></div>}{view==='settings'&&<section id="settings"><AdminSettings/><ContentPostManagement/><WebsiteManagement/><EmployeeManagement/><OperationsControlCenter/>{session.user.app_metadata?.role==='super_admin'&&<SuperAdminPanel/>}</section>}</main>
  </div></div>
  {notificationDetail&&<RecordDetailModal record={notificationDetail} onClose={()=>setNotificationDetail(null)}/>}</>;
}

function Nav({view,id,onClick,children}:{view:View;id:View;onClick:(view:View)=>void;children:ReactNode}){return <button className={view===id?'selected':''} onClick={()=>onClick(id)}><span>{children}</span></button>}
function StatusSelect({value,onChange}:{value:string;onChange:(value:string)=>void}){return <select value={value} onClick={event=>event.stopPropagation()} onChange={event=>onChange(event.target.value)} aria-label="Update status"><option>Pending</option><option>Open</option><option>Sent</option><option>Read</option><option>Confirmed</option><option>Completed</option><option>Resolved</option><option>Closed</option><option>Cancelled</option></select>}
function Operations<T extends RecordItem>({title,rows,empty,render}:{title:string;rows:T[];empty:string;render:(row:T)=>ReactNode}){const[opened,setOpened]=useState<T|null>(null);return <section className="panel data-panel"><div className="panel-heading"><div><p className="eyebrow">OPERATIONS</p><h2>{title}</h2></div><span>{rows.length} total</span></div>{rows.length?<div className="records">{rows.map(row=><article className="openable-record" key={row.id} onClick={()=>setOpened(row)}>{render(row)}</article>)}</div>:<p className="empty">{empty}</p>}{opened&&<RecordDetailModal record={opened} onClose={()=>setOpened(null)}/>}</section>}
function NotificationSummary({bookings,messages,requests,onOpen}:{bookings:Booking[];messages:Message[];requests:Request[];onOpen:(record:RecordItem)=>void}){return <div className="popover notifications notification-summary"><b>Notification centre</b><small>New and upcoming activity</small>{bookings.map(row=><button key={row.id} onClick={()=>onOpen(row)}><strong>Upcoming booking</strong><span>{row.customers?.name??'Customer'} · {row.services?.name??'Service'}</span></button>)}{messages.map(row=><button key={row.id} onClick={()=>onOpen(row)}><strong>New message</strong><span>{row.customers?.name??'Customer'} · {row.subject}</span></button>)}{requests.map(row=><button key={row.id} onClick={()=>onOpen(row)}><strong>Open request</strong><span>{row.customers?.name??'Customer'} · {row.request_type}</span></button>)}{!bookings.length&&!messages.length&&!requests.length&&<p>No new or upcoming items.</p>}</div>}
function RecordDetailModal({record,onClose}:{record:RecordItem;onClose:()=>void}){const customer=record.customers;const body='body' in record?record.body:'description' in record?record.description:record.notes??'No additional notes.';const subject='subject' in record?record.subject:'request_type' in record?record.request_type:record.services?.name??'Booking';return <div className="record-modal-backdrop" onClick={onClose}><article className="record-modal" onClick={event=>event.stopPropagation()}><button className="record-modal-close" onClick={onClose}>×</button><p className="eyebrow">RECORD DETAILS</p><h2>{subject}</h2><p>{body}</p><div className="record-contact"><b>{customer?.name??'Customer'}</b><span>{customer?.email??'No email address'}</span><span>{customer?.phone??'No phone number'}</span></div><div className="record-actions">{customer?.email&&<a href={`mailto:${customer.email}?subject=${encodeURIComponent(`Re: ${subject}`)}`}>Reply</a>}{customer?.phone&&<a href={`tel:${customer.phone}`}>Call</a>}</div></article></div>}
